Repository onosproject/onos-config, pull requests merged in 2019-12, with the labels that each got.

#929 Refactoring ModelGenerator and updating plugins documentation
  docs/modelplugin.md
  modelplugin/Devicesim-1.0.0.env
  modelplugin/ModelGenerator.sh
  modelplugin/Stratum-1.0.0.env
  modelplugin/TestDevice-1.0.0.env
  modelplugin/TestDevice-2.0.0.env
  pkg/cli/models.go
Labels: bug :beetle:

#930 Adding inital configuration set on the device
  pkg/controller/change/device/controller_test.go
  pkg/events/events.go
  pkg/manager/manager.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
  pkg/utils/values/gnmiChange.go
Labels: enhancement

#931 Skipping manager deep tests - were causing intermittent errors on travis
  pkg/manager/manager_deep_test.go
Labels: bug :beetle:

#940 Adding readiness and liveness probes for helm chart
  deployments/helm/onos-config/templates/deployment.yaml
Labels: enhancement

#943 Wilcard get on the NB reports all devices, also un-connected.
  pkg/manager/getconfig.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/gnmi_test.go
Labels: bug :beetle:

#944 Reporting device disconnection
  Makefile
  pkg/southbound/synchronizer/synchronizer.go
Labels: bug :beetle:

#949 Fixing "onos config get device-changes <deviceid>"
  pkg/northbound/diags/diags.go
Labels: bug :beetle:

#945 Split the makefile in to debug and latest
  Makefile
  build/base/Dockerfile
  build/onos-config-debug/Dockerfile
  build/plugins/Dockerfile
Labels: enhancement

#952 Checking that the requested rollback change is the last one
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
Labels: bug :beetle:

#951 Adding multiple targets examples
  docs/gnmi.md
Labels: enhancement

#947 Retry device state updates to avoid inconsistent states
  go.mod
  go.sum
  pkg/manager/devicehandler.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: bug :beetle:

#948 Fix bugs in controller retries
  api/types/change/device/types.pb.go
  api/types/change/device/types.proto
  api/types/change/network/types.pb.go
  api/types/change/network/types.proto
  docs/api/types_change_device.md
  docs/api/types_change_network.md
  pkg/controller/change/network/controller.go
  pkg/controller/change/network/controller_test.go
  pkg/manager/manager.go
Labels: WIP, bug :beetle:

#956 Retry southbound connections
  go.mod
  go.sum
  pkg/southbound/clientManager.go
  pkg/southbound/clientManager_test.go
  pkg/southbound/defs.go
  pkg/southbound/gnmiClient.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/test/mocks/southbound/target_mock.go
Labels: bug :beetle:

#968 Fixing logs for device errors in factory.
  pkg/southbound/synchronizer/factory.go
Labels: bug :beetle:

#976 Added DeviceType to DeviceSnapshot & Snapshot
  api/types/snapshot/device/types.pb.go
  api/types/snapshot/device/types.proto
  docs/api/types_snapshot_device.md
  pkg/controller/snapshot/device/controller.go
  pkg/controller/snapshot/device/controller_test.go
  pkg/controller/snapshot/device/watcher_test.go
  pkg/controller/snapshot/network/controller.go
  pkg/controller/snapshot/network/controller_test.go
  pkg/manager/manager.go
  pkg/test/mocks/store/device_snapshot_store_mock.go
Labels: enhancement

#975 Add snaphots to the Device Cache too
  cmd/onos-config/onos-config.go
  pkg/manager/manager_deep_test.go
  pkg/store/device/cache/cache.go
  pkg/store/device/cache/cache_test.go
Labels: enhancement

#980 Removing helm charts and updating docs.
  deployments/helm/onos-config/.helmignore
  deployments/helm/onos-config/Chart.yaml
  deployments/helm/onos-config/README.md
  deployments/helm/onos-config/files/certs/README.md
  deployments/helm/onos-config/files/certs/tls.cacrt
  deployments/helm/onos-config/files/certs/tls.crt
  deployments/helm/onos-config/files/certs/tls.key
  deployments/helm/onos-config/templates/_helpers.tpl
  deployments/helm/onos-config/templates/deployment.yaml
  deployments/helm/onos-config/templates/ingress.yaml
  deployments/helm/onos-config/templates/partitionset.yaml
  deployments/helm/onos-config/templates/secret.yaml
  deployments/helm/onos-config/templates/service.yaml
  deployments/helm/onos-config/values.yaml
  docs/deployment.md
Labels: enhancement

#979 Handling Topo device UPDATE and DELETE
  pkg/events/events.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
Labels: bug :beetle:

#990 Ensure config reconnects to devices on disconnection
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
Labels: bug :beetle:

#988 Fix deadlock in device cache
  pkg/store/device/cache/cache.go
Labels: bug :beetle:

#991 Ensure network change stream remains open until condition is met
  test/gnmi/gnmiutils.go
Labels: bug :beetle:

#992 Update onos-test dependency
  go.mod
  go.sum
Labels: bug :beetle:

#963 Add integration test for offline devices
  test/gnmi/offlinedevicetest.go
Labels: enhancement

#973 Add integration test for set() is called on a device in the topo but offline
  go.sum
  test/gnmi/offlineintopotest.go
Labels: do not merge :warning:, enhancement

#993 Add test utility function to wait for config to connect to device
  test/gnmi/gnmiutils.go
  test/gnmi/offlineintopotest.go
  test/gnmi/singlestatetest.go
  test/gnmi/subscribetest.go
  test/gnmi/transactiontest.go
Labels: bug :beetle:

#994 Increment incarnation number on rollback to avoid deadlock
  pkg/manager/rollbackconfig.go
Labels: bug :beetle:

#995 Do not exit device cache watch loop when device is not found
  pkg/controller/change/device/watcher.go
  pkg/controller/change/network/watcher.go
Labels: bug :beetle:
