Repository onosproject/onos-config, pull requests merged in 2019-10, with the labels that each got.

#705 Added in unit tests for Synchronizer
  go.mod
  go.sum
  pkg/southbound/defs.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
  pkg/southbound/synchronizer/target_mock_test.go
Labels: enhancement

#709 Updated synchronizer tests further
  pkg/southbound/clientManager.go
  pkg/southbound/defs.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
  pkg/southbound/synchronizer/target_mock_test.go
  pkg/utils/values/gnmiValueUtil.go
Labels: enhancement

#711 Added in unit tests for CLI GetConfigs and GetChanges
  pkg/cli/changes.go
  pkg/cli/configs.go
  pkg/cli/configs_test.go
  pkg/cli/mockclients_test.go
  pkg/northbound/diags/diags.go
Labels: enhancement

#710 Refactoring ModelGenerator script
  docs/modelplugin.md
  modelplugin/Devicesim-1.0.0.env
  modelplugin/ModelGenerator.sh
  modelplugin/Stratum-1.0.0.env
  modelplugin/TestDevice-1.0.0.env
  modelplugin/TestDevice-2.0.0.env
  modelplugin/yang/TestDevice-1.0.0/test1@2018-02-20.yang
  modelplugin/yang/TestDevice-2.0.0/test1@2019-06-10.yang
Labels: enhancement

#714 Adding in enum for GetStateMode - needed so that plugins can build in following patch
  pkg/modelregistry/modelregistry.go
Labels: enhancement

#716 Added Device Configuration specific links in config docs
  docs/README.md
Labels: enhancement

#715 Updating ConvertJSON to handle non-openconfig yang model for opstate
  pkg/modelregistry/jsonvalues/convertJsonRo_test.go
  pkg/modelregistry/jsonvalues/convertJsonTdRo_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/modelregistry/jsonvalues/testdata/sample-testdevice-opstate.json
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
Labels: bug :beetle:

#702 Updated synchronizer with new scheme for getting OpState Fixes #493
  build/plugins/Dockerfile
  modelplugin/Devicesim-1.0.0/modelmain.go
  modelplugin/ModelGenerator.sh
  modelplugin/Stratum-1.0.0/modelmain.go
  modelplugin/TestDevice-1.0.0/modelmain.go
  modelplugin/TestDevice-2.0.0/modelmain.go
  pkg/manager/manager.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistryTestDevice1_test.go
  pkg/modelregistry/modelregistryTestDevice2_test.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/admin/admin.go
  pkg/northbound/diags/diags.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
Labels: bug :beetle:

#704 Device state propagation
  go.mod
  go.sum
  pkg/events/events.go
  pkg/events/responseevent.go
  pkg/manager/manager.go
  pkg/manager/setconfig.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/topocache/topocache.go
Labels: WIP

#724 Enabling multiple code generators
  build/licensing/boilerplate.generatego.txt
  build/licensing/boilerplate.py
  pkg/southbound/synchronizer/target_mock_test.go
Labels: enhancement

#730 Removing CLI `onos config config set/get` Partly fixes issue 18 of onos-cli
  modelplugin/Devicesim-1.0.0/devicesim_1_0_0/generated.go
  modelplugin/ModelGenerator.sh
  modelplugin/Stratum-1.0.0/stratum_1_0_0/generated.go
  modelplugin/TestDevice-1.0.0/testdevice_1_0_0/generated.go
  modelplugin/TestDevice-2.0.0/testdevice_2_0_0/generated.go
  pkg/cli/client.go
  pkg/cli/config.go
  pkg/cli/models.go
  pkg/cli/models_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin.pb.go
  pkg/northbound/admin/admin.proto
  pkg/southbound/synchronizer/target_mock_test.go
Labels: bug :beetle:

#735 Extension for Disconnected devices
  docs/gnmi_extensions.md
  pkg/northbound/gnmi/extensions.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
Labels: enhancement

#741 Separated out the TypedValue from Value
  pkg/controller/change/device/controller_test.go
  pkg/controller/change/network/controller_test.go
  pkg/controller/change/network/watcher_test.go
  pkg/southbound/topocache/topocache.go
  pkg/store/change/change.go
  pkg/store/change/changevalue.go
  pkg/store/change/configvalue.go
  pkg/store/change/device/store_test.go
  pkg/store/change/network/store_test.go
  pkg/store/change/typedvalue.go
  pkg/store/configuration.go
  pkg/store/networkconfiguration.go
  pkg/store/stores.go
  pkg/types/change/device/types.pb.go
  pkg/types/change/device/types.proto
  pkg/utils/values/gnmiChange.go
  pkg/utils/values/gnmiValueUtil.go
Labels: enhancement

#744 Ensure device changes are created in network change order
  pkg/controller/change/network/controller.go
Labels: bug :beetle:

#748 Totally remove native TypedValue - replace with protobuf one from Types
  build/bin/coveralls-coverage
  cmd/profiling/profile-config.go
  configs/changeStore-sample.json
  configs/configStore-sample.json
  pkg/cli/changes.go
  pkg/cli/configs_test.go
  pkg/cli/devicetree.go
  pkg/cli/opstate_test.go
  pkg/dispatcher/dispatcher_test.go
  pkg/events/events_test.go
  pkg/events/operationalevent.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
  pkg/manager/setconfig.go
  pkg/modelregistry/jsonvalues/convertJsonRo_test.go
  pkg/modelregistry/jsonvalues/convertJsonRw_test.go
  pkg/modelregistry/jsonvalues/convertJsonTdRo_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistryDeviceSim1_test.go
  pkg/modelregistry/modelregistryTestDevice1_test.go
  pkg/modelregistry/modelregistryTestDevice2_test.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/northbound/testUtils.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/factory_test.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
  pkg/store/change/change_test.go
  pkg/store/change/changevalue.go
  pkg/store/change/configvalue.go
  pkg/store/configuration.go
  pkg/store/jsonToValues.go
  pkg/store/jsonToValues_test.go
  pkg/store/store-api_test.go
  pkg/store/tree.go
  pkg/store/tree_test.go
  pkg/types/change/device/typedvalue.go
  pkg/types/change/device/typedvalue_test.go
  pkg/types/change/device/types.pb.go
  pkg/types/change/device/types.proto
  pkg/utils/values/gnmiChange_test.go
  pkg/utils/values/gnmiValueUtil.go
  pkg/utils/values/gnmiValueUtil_test.go
Labels: enhancement

#755 Removed the deprecated types ConfigValue, ChangeValue and ValueCollection
  cmd/profiling/profile-config.go
  configs/changeStore-sample.json
  configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  pkg/cli/changes.go
  pkg/cli/changes_test.go
  pkg/cli/configs_test.go
  pkg/cli/devicetree.go
  pkg/cli/opstate_test.go
  pkg/controller/change/device/controller_test.go
  pkg/controller/change/network/controller_test.go
  pkg/controller/change/network/watcher_test.go
  pkg/manager/getconfig.go
  pkg/manager/getstate.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
  pkg/modelregistry/jsonvalues/convertJsonRo_test.go
  pkg/modelregistry/jsonvalues/convertJsonRw_test.go
  pkg/modelregistry/jsonvalues/convertJsonTdRo_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
  pkg/store/change/change.go
  pkg/store/change/change_test.go
  pkg/store/change/changevalue.go
  pkg/store/change/device/store_test.go
  pkg/store/change/network/store_test.go
  pkg/store/configuration.go
  pkg/store/jsonToValues.go
  pkg/store/jsonToValues_test.go
  pkg/store/store-api_test.go
  pkg/store/tree.go
  pkg/store/tree_test.go
  pkg/types/change/device/typedvalue_test.go
  pkg/types/change/device/types.pb.go
  pkg/types/change/device/types.proto
  pkg/types/change/device/value.go
  pkg/utils/values/gnmiChange.go
  pkg/utils/values/gnmiChange_test.go
Labels: enhancement

#754 Refactor change stores to use IndexedMap primitives
  go.mod
  go.sum
  pkg/controller/change/device/controller_test.go
  pkg/controller/change/device/partitioner_test.go
  pkg/controller/change/network/controller.go
  pkg/controller/change/network/controller_test.go
  pkg/controller/change/network/watcher_test.go
  pkg/store/change/device/store.go
  pkg/store/change/device/store_test.go
  pkg/store/change/network/store.go
  pkg/store/change/network/store_test.go
  pkg/types/change/device/types.go
  pkg/types/change/network/types.go
Labels: enhancement

#750 Adding new Change and Network store to manager
  cmd/onos-config/onos-config.go
  pkg/manager/device_chages_store_mock_test.go
  pkg/manager/device_store_mock_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/network_chages_store_mock_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/testUtils.go
Labels: enhancement

#760 Replaced types in NBI diags with new Types from stores
  pkg/cli/changes.go
  pkg/cli/changes_test.go
  pkg/cli/configs_test.go
  pkg/cli/devicetree.go
  pkg/cli/devicetree_test.go
  pkg/cli/opstate.go
  pkg/cli/opstate_test.go
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin.pb.go
  pkg/northbound/admin/admin.proto
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags.pb.go
  pkg/northbound/diags/diags.proto
  pkg/northbound/diags/diags_test.go
  pkg/utils/values/gnmiValueUtil.go
Labels: enhancement

#763 Translation of new device.Change to gNMI SetRequest
  pkg/utils/values/gnmiChange.go
  pkg/utils/values/gnmiChange_test.go
Labels: enhancement

#761 gNMI Set requests writes also to new atomix stores
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/types/change/network/network.go
Labels: enhancement

#767 Set SB plumbing, Get and Validate in parallel with Atomix
  pkg/controller/change/device/controller.go
  pkg/manager/getconfig.go
  pkg/manager/manager.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/store/change/device/utils.go
  pkg/utils/values/gnmiChange_test.go
Labels: enhancement

#768 Continuing of the extending on the NBI
  docs/cli.md
  pkg/cli/crud.go
  pkg/cli/devicechanges.go
  pkg/cli/devicechanges_test.go
  pkg/cli/mockclients_test.go
  pkg/cli/networkchanges.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags.pb.go
  pkg/northbound/diags/diags.proto
  pkg/northbound/diags/diags_new_test.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/testUtils.go
  pkg/utils/wildcards.go
  pkg/utils/wildcards_test.go
Labels: enhancement

#780 Removed dependency on onos-config from model plugin to speed builds
  build/plugins/Dockerfile
  modelplugin/Devicesim-1.0.0/modelmain.go
  modelplugin/ModelGenerator.sh
  modelplugin/Stratum-1.0.0/modelmain.go
  modelplugin/TestDevice-1.0.0/modelmain.go
  modelplugin/TestDevice-2.0.0/modelmain.go
  pkg/manager/manager_test.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
Labels: bug :beetle:

#781 Change snapshot to have a PathValue rather than ChangeValue
  pkg/controller/snapshot/device/controller.go
  pkg/controller/snapshot/device/controller_test.go
  pkg/types/change/device/types.pb.go
  pkg/types/change/device/types.proto
  pkg/types/snapshot/device/types.pb.go
  pkg/types/snapshot/device/types.proto
Labels: enhancement

#786 Fixed conflicts on 775 but had to push them back on my branch
  build/bin/compile-protos.sh
  pkg/cli/mockclients_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/cli/snapshot.go
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin.pb.go
  pkg/northbound/admin/admin.proto
Labels: enhancement

#789 Set Response based on new atomix stores
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
Labels: enhancement

#792 Removing probematic test conditiion in snapshot device controller
  pkg/controller/snapshot/device/controller_test.go
Labels: bug :beetle:

#794 Adding feedback for rollback changes
  pkg/manager/rollbackconfig.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
Labels: enhancement

#795 Change python script to use python3
  build/licensing/boilerplate.py
  build/licensing/boilerplate.py.txt
Labels: enhancement

#772 Adding deviceType to Change
  pkg/manager/manager.go
  pkg/types/change/device/types.pb.go
  pkg/types/change/device/types.proto
  pkg/utils/values/gnmiChange_test.go
Labels: enhancement

#804 Ensure parent NetworkChange ID is produced to NetworkChange controller on DeviceChange event
  pkg/controller/change/network/watcher.go
  pkg/controller/change/network/watcher_test.go
Labels: bug :beetle:

#807 Added a Get option for DeviceChanges and NetworkChanges
  pkg/cli/changes.go
  pkg/cli/configs.go
  pkg/cli/crud.go
  pkg/cli/devicechanges.go
  pkg/cli/devicechanges_test.go
  pkg/cli/mockclients_test.go
  pkg/cli/net-changes.go
  pkg/cli/networkchanges.go
  pkg/cli/networkchanges_test.go
  pkg/cli/opstate.go
  pkg/cli/rollback.go
  pkg/cli/root_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags.pb.go
  pkg/northbound/diags/diags.proto
Labels: enhancement

#808 Enabling rollback to be done on a per device basis in the device change controller
  pkg/controller/change/device/controller.go
  pkg/store/change/device/utils/utils.go
  pkg/store/change/device/utils/utils_test.go
Labels: bug :beetle:

#810 Added more tests for computeDelta, with some slight changes to it
  pkg/controller/change/device/computedelta_test.go
  pkg/controller/change/device/controller.go
  pkg/controller/change/device/controller_test.go
Labels: enhancement

#812 Added in check for read only
  cmd/onos-config/onos-config.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/northbound/diags/diags_new_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/testUtils.go
  pkg/store/device/cache_mock.go
Labels: enhancement

#790 Skip empty snapshots to avoid infinite reconciliation loop
  pkg/controller/snapshot/network/controller.go
Labels: enhancement

#816 Fixed some errors in manager_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/set.go
Labels: enhancement

#817 Set() on NB checks type and version ext with device cache first
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/store/store-api.go
Labels: enhancement

#820 Minor update to setconfig.go to help merging of SB and NB patches
  pkg/manager/setconfig.go
Labels: enhancement

#814 Moving the southbound connection to controller.go for Atomix based stores
  pkg/controller/change/device/controller.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/set.go
  pkg/southbound/clientManager.go
  pkg/southbound/defs.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: WIP, do not merge :warning:

#823 Fixed up so that integration tests run again
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/subscribe.go
Labels: enhancement

#827 Changed how checkForReadOnly works
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/southbound/synchronizer/factory.go
Labels: bug :beetle:

#819 Removing unused CLI commands for old change, config and netchanges
  pkg/cli/changes.go
  pkg/cli/changes_test.go
  pkg/cli/configs.go
  pkg/cli/configs_test.go
  pkg/cli/crud.go
  pkg/cli/devicetree.go
  pkg/cli/devicetree_test.go
  pkg/cli/mockclients_test.go
  pkg/cli/net-changes.go
  pkg/cli/net-changes_test.go
  pkg/cli/rollback.go
  pkg/cli/rollback_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin.pb.go
  pkg/northbound/admin/admin.proto
  pkg/northbound/admin/admin_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags.pb.go
  pkg/northbound/diags/diags.proto
  pkg/northbound/diags/diags_test.go
Labels: enhancement

#831 Removed old classes for NetChanges and Configuration. Also removed loading of old stores from Helm charts
  cmd/profiling/profile-config.go
  deployments/helm/onos-config/files/configs/README.md
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/networkStore-sample.json
  deployments/helm/onos-config/templates/configmap.yaml
  deployments/helm/onos-config/templates/deployment.yaml
  pkg/store/change/change.go
  pkg/store/change/change_test.go
  pkg/store/change/device/store_test.go
  pkg/store/configuration.go
  pkg/store/networkconfiguration.go
  pkg/store/store-api.go
  pkg/store/store-api_test.go
Labels: enhancement
