Repository onosproject/onos-config, pull requests merged in 2019-09, with the labels that each got.

#555 Adding -race flag to check for race conditions
  Makefile
Labels: WIP, do not merge :warning:

#674 Reduced size of latest by not copying debug plugins
  Makefile
  build/onos-config-debug/Dockerfile
Labels: bug :beetle:

#679 Updating docs to work with MkDocs
  docs/cli.md
  docs/gnmi.md
  docs/gnmi_extensions.md
  docs/license_goland.md
  docs/modelplugin.md
  docs/pull_requests.md
Labels: bug :beetle:

#682 Fixed link in docs - admin and proto
  docs/gnmi_extensions.md
Labels: bug :beetle:

#686 Refactoring of events to be defined as interfaces not structs Fixes #680
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/events/configevent.go
  pkg/events/events.go
  pkg/events/events_test.go
  pkg/events/operationalevent.go
  pkg/events/responseevent.go
  pkg/events/topoevent.go
  pkg/manager/rollbackconfig.go
  pkg/manager/setconfig.go
  pkg/northbound/diags/diags.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/northbound/testUtils.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/topocache/topocache.go
Labels: bug :beetle:

#688 Replace Create with New in 'store' package as this is more conventional for Go
  cmd/profiling/profile-config.go
  pkg/cli/changes.go
  pkg/cli/devicetree.go
  pkg/dispatcher/dispatcher_test.go
  pkg/events/events_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/setconfig.go
  pkg/modelregistry/jsonvalues/convertJsonRo_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/northbound/testUtils.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/change/change.go
  pkg/store/change/change_test.go
  pkg/store/change/changevalue.go
  pkg/store/change/typedvalue.go
  pkg/store/change/typedvalue_test.go
  pkg/store/configuration.go
  pkg/store/jsonToValues.go
  pkg/store/store-api_test.go
  pkg/store/stores.go
  pkg/store/tree_test.go
  pkg/utils/values/gnmiValueUtil.go
  pkg/utils/values/gnmiValueUtil_test.go
Labels: enhancement

#690 Changed 'onos config get configs' to take optional config id Fixes #664
  pkg/cli/configs.go
Labels: bug :beetle:

#701 Hold for device reply before notifying subscribers of a change.
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/southbound/topocache/topocache.go
Labels: bug :beetle:

#703 Fix for integration test on subscribe pending device response
  pkg/events/events.go
  pkg/manager/rollbackconfig.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/subscribe.go
Labels: bug :beetle:
