Repository onosproject/onos-config, pull requests merged in 2019-06, with the labels that each got.

#294 Changing references to certs because they were removed
  docs/gnmi.md
  docs/run.md
  pkg/certs/default-certificates.go
Labels: bug

#264 Cache for operational state on SB.
  cmd/southbound_main/README.md
  cmd/southbound_main/southbound_main.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/events/events.go
  pkg/manager/manager.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/service.go
  pkg/northbound/gnmi/subscribe.go
  pkg/southbound/clientManager.go
  pkg/southbound/clientManager_test.go
  pkg/southbound/defs.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/utils/gnmiPathUtils.go
Labels: enhancement

#299 Adding ability to administratively add/remove/list devices.
  cmd/admin/devices/devices.go
  docs/admin.md
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin_devices.go
  pkg/northbound/proto/admin.pb.go
  pkg/northbound/proto/admin.proto
  pkg/southbound/topocache/topocache.go
  pkg/southbound/topocache/topocache_test.go
Labels: enhancement

#306 Refactored onos-config.go and manager.go for easier testing
  cmd/onos-config/onos-config.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/northbound/gnmi/gnmi_test.go
Labels: enhancement

#307 Add setting of a default value for SoftwareVersion
  deployments/helm/onos-config/templates/configmap.yaml
Labels: bug

#302 Added in original configuration for stratum
  configs/changeStore-sample.json
  configs/configStore-sample.json
  configs/deviceStore-sample.json
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  pkg/northbound/gnmi/get_test.go
Labels: enhancement

#319 Reimplemented tree.go and added unit tests
  cmd/diags/devicetree/devicetree.go
  pkg/manager/getconfig.go
  pkg/manager/manager_test.go
  pkg/manager/tree.go
  pkg/northbound/gnmi/get.go
  pkg/store/configuration.go
  pkg/store/store-api_test.go
  pkg/store/tree.go
  pkg/store/tree_test.go
Labels: enhancement

#320 Skeletal CLI implementation using Cobra/Viper frameworks.
  Makefile
  cmd/onos/main.go
  pkg/cli/command/changes.go
  pkg/cli/command/completion.go
  pkg/cli/command/config.go
  pkg/cli/command/configs.go
  pkg/cli/command/devices.go
  pkg/cli/command/devicetree.go
  pkg/cli/command/net-changes.go
  pkg/cli/command/output.go
  pkg/cli/command/rollback.go
  pkg/cli/command/root.go
  pkg/cli/onosctl.go
Labels: enhancement

#323 Removing one layer of channel on gNMI NB subscribe
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/service.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/store/change/change_test.go
Labels: enhancement

#332 Lower timeouts for devices, remove return in Factory
  configs/deviceStore-sample.json
  deployments/helm/onos-config/files/configs/deviceStore-sample.json
  deployments/helm/onos-config/templates/configmap.yaml
  pkg/northbound/admin/admin_devices.go
  pkg/southbound/clientManager.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/topocache/topocache.go
Labels: enhancement

#321 Added in YGOT with a sample YANG file
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/onos-config/onos-config.go
  configs/changeStore-sample.json
  configs/configStore-sample.json
  modelplugin/ModelGenerator.sh
  modelplugin/TestDevice-1.0.0/modelmain.go
  modelplugin/TestDevice-1.0.0/testdevice_1_0_0/generated.go
  modelplugin/TestDevice-2.0.0/modelmain.go
  modelplugin/TestDevice-2.0.0/testdevice_2_0_0/generated.go
  modelplugin/yang/test1@2018-02-20.yang
  modelplugin/yang/test1@2019-06-10.yang
  pkg/manager/manager.go
  pkg/manager/modelregistry.go
  pkg/manager/setconfig.go
  pkg/models/models.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/service.go
  pkg/northbound/gnmi/service_test.go
  pkg/store/store-api_test.go
Labels: enhancement

#337 Update the docs for the CLI and obsoleted admin.md and diags.md
  docs/admin.md
  docs/cli.md
  docs/diags.md
  docs/run.md
Labels: enhancement

#336 Added Dockerfile for building onos-cli image
  Makefile
  build/onos-cli/Dockerfile
  pkg/cli/command/root.go
Labels: enhancement

#338 Updated docs to reflect the new 'onos' CLI
  README.md
  docs/deployment.md
  docs/images/design.png
Labels: enhancement

#339 Add PartitionSet to onos-config Helm chart
  deployments/helm/onos-config/templates/deployment.yaml
  deployments/helm/onos-config/templates/partitionset.yaml
  deployments/helm/onos-config/values.yaml
Labels: enhancement

#341 Moving ModelData out of Configuration object - now in the modelplugin
  .gitignore
  cmd/diags/devicetree/devicetree.go
  configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/README.md
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/deviceStore-sample.json
  pkg/cli/command/devicetree.go
  pkg/manager/manager_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/proto/diags.proto
  pkg/store/configuration.go
  pkg/store/store-api_test.go
  pkg/store/stores.go
Labels: enhancement

#342 Adding tests for the DeviceInventoryService NB
  Makefile
  pkg/northbound/admin/admin_devices.go
  pkg/northbound/admin/admin_test.go
  pkg/northbound/proto/admin.pb.go
  pkg/northbound/proto/admin.proto
Labels: enhancement

#345 Fix Subscribe
  pkg/dispatcher/dispatcher.go
  pkg/southbound/clientManager.go
  pkg/southbound/clientManager_test.go
  pkg/southbound/gnmiBaseClient.go
  pkg/southbound/gnmiBaseClient_test.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: enhancement

#343 Deleted the old admin and diags commands replaced by the new 'onos' CLI
  cmd/admin/devices/devices.go
  cmd/admin/net-changes/net-changes.go
  cmd/admin/rollback/rollback.go
  cmd/diags/changes/changes.go
  cmd/diags/configs/configs.go
  cmd/diags/devicetree/devicetree.go
Labels: enhancement

#344 Added docs for onos-cli container to deployment.md
  docs/deployment.md
Labels: enhancement

#348 Created protoc-go docker image for just compiling protobufs into Go
  build/protoc-go/Dockerfile
  build/protoc-go/README.md
  pkg/northbound/proto/compile-protos.sh
Labels: enhancement

#350 Streamlined the Makefile to address #347
  Makefile
  build/dev-docker/README.md
  build/dev-docker/compile-protos.sh
  build/golang-build/Dockerfile
  build/golang-build/README.md
  build/golang-build/dep-linux-amd64.sha256
  build/protoc-go/README.md
  docs/build.md
  docs/prerequisites.md
  pkg/northbound/proto/diags.pb.go
Labels: enhancement

#351 Updating .travis.yml in preparation for the new golang-build image
  .travis.yml
Labels: enhancement

#355 Adding in admin interface for Model plugins Fixes #334
  build/protoc-go/Dockerfile
  cmd/onos-config/onos-config.go
  docs/cli.md
  docs/prerequisites.md
  docs/run.md
  pkg/cli/command/models.go
  pkg/cli/command/rollback.go
  pkg/cli/command/root.go
  pkg/manager/modelregistry.go
  pkg/northbound/admin/admin.go
  pkg/northbound/proto/admin.pb.go
  pkg/northbound/proto/admin.proto
Labels: enhancement

#356 gNMI Northbound Error propagation
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
Labels: enhancement

#365 Properly unregistering device
  pkg/dispatcher/dispatcher.go
  pkg/northbound/gnmi/subscribe.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: bug :beetle:

#362 Added in docs for Model Plugins and gNMI Extensions. Fixes #358
  README.md
  docs/cli.md
  docs/gnmi.md
  docs/gnmi_extensions.md
  docs/images/onos-config-internals.png
  docs/modelplugin.md
  docs/run.md
  modelplugin/ModelGenerator.sh
  modelplugin/yang/README.md
Labels: enhancement

#353 Support DEBUG variable to build binaries with debugging support enabled
  Makefile
  build/onos-config-debug/Dockerfile
  deployments/helm/onos-config/templates/deployment.yaml
  deployments/helm/onos-config/values.yaml
Labels: enhancement

#363 Enable CGO to allow plugins run in Docker
  Makefile
  build/onos-config-debug/Dockerfile
  build/onos-config/Dockerfile
Labels: bug :beetle:

#366 gNMI Northbound Poll testing
  pkg/northbound/gnmi/subscribe_test.go
Labels: enhancement

#367 Remove the sleep from northbound/admin tests Fixes #354
  cmd/onos-config/onos-config.go
  pkg/northbound/admin/admin_test.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/server.go
  pkg/northbound/testUtils.go
Labels: bug :beetle:

#368 Moving project to go modules
  Gopkg.lock
  Gopkg.toml
  Makefile
  docs/modelplugin.md
  docs/prerequisites.md
  go.mod
  go.sum
  modelplugin/Devicesim-1.0.0/modelmain.go
  modelplugin/ModelGenerator.sh
  modelplugin/TestDevice-1.0.0/modelmain.go
  modelplugin/TestDevice-2.0.0/modelmain.go
Labels: enhancement, help wanted

#369 Replaced all standard log entries with klog Fixes #324
  cmd/onos-config/onos-config.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/events/configevent.go
  pkg/events/topoevent.go
  pkg/manager/getconfig.go
  pkg/manager/manager_test.go
  pkg/manager/modelregistry.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/northbound/testUtils.go
  pkg/southbound/clientManager.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/change/change_test.go
  pkg/store/store-api_test.go
Labels: enhancement

#370 Updated manager to validate configs at startup Fixes #357
  cmd/onos-config/onos-config.go
  configs/changeStore-sample.json
  configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  docs/run.md
  modelplugin/Devicesim-1.0.0/modelmain.go
  modelplugin/ModelGenerator.sh
  modelplugin/TestDevice-2.0.0/modelmain.go
  pkg/manager/manager.go
  pkg/northbound/diags/diags_test.go
  pkg/store/tree.go
Labels: bug :beetle:

#373 Enabling deletion of single paths
  docs/gnmi.md
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
Labels: bug :beetle:, enhancement

#381 Read exactly 4 replies. Fix #377
  pkg/northbound/gnmi/subscribe_test.go
Labels: bug :beetle:

#382 Optimize docker build
  Makefile
  build/base/Dockerfile
  build/onos-cli/Dockerfile
  build/onos-config-debug/Dockerfile
  build/onos-config/Dockerfile
  build/onos-it/Dockerfile
  go.mod
  go.sum
Labels: enhancement

#387 Detect test job complete when pod completes between polling intervals
  test/runner/controller.go
Labels: bug :beetle:

#388 Add 'make kind' command
  Makefile
Labels: enhancement

#394 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#391 Inserting spaces in log. Fixes: #390
  cmd/onos-config/onos-config.go
  cmd/profiling/profile-config.go
  pkg/dispatcher/dispatcher.go
  pkg/dispatcher/dispatcher_test.go
  pkg/events/configevent.go
  pkg/manager/getconfig.go
  pkg/manager/manager.go
  pkg/manager/modelregistry.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/northbound/server.go
  pkg/northbound/testUtils.go
  pkg/southbound/clientManager.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/store-api_test.go
Labels: bug :beetle:

#392 Setting pre-existing config to device. Fixes #379
  docs/gnmi.md
  pkg/manager/manager.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/change/change.go
Labels: enhancement

#399 Removing logs and adding docs for kind or minikube
  docs/prerequisites.md
  pkg/southbound/synchronizer/synchronizer.go
Labels: enhancement

#397 Add separate cluster management commits to onit
  docs/testing.md
  go.mod
  go.sum
  pkg/manager/manager.go
  test/configs/default.json
  test/configs/device/default.json
  test/configs/simulator-1.json
  test/configs/simulator-3.json
  test/configs/store/default.json
  test/runner/cli.go
  test/runner/config.go
  test/runner/controller.go
Labels: enhancement

#404 Add commands to read logs from onos-config nodes/simulators/partitions
  docs/testing.md
  test/runner/cli.go
  test/runner/controller.go
  test/runner/onos-config.go
  test/runner/partitions.go
  test/runner/test.go
Labels: enhancement

#400 Integration test for transactions and rollback
  test/env/env.go
  test/integration/gnmiutils.go
  test/integration/singlepathtest.go
  test/integration/transactiontest.go
Labels: enhancement

#412 Adding an integration test for subscribe stream
  test/integration/subscribetest.go
Labels: enhancement

#420 Including Kind instructions
  docs/testing.md
Labels: enhancement

#439 Notification for device when administratively added
  pkg/southbound/topocache/topocache.go
Labels: bug :beetle:

#444 Use admin interface to add devices to nodes in onit
  Makefile
  build/onos-config-debug/Dockerfile
  go.sum
  test/runner/client.go
  test/runner/cluster.go
  test/runner/controller.go
  test/runner/onos-config.go
Labels: enhancement

#427 Add "onit fetch" command to download logs
  test/runner/cli.go
  test/runner/cluster.go
Labels: enhancement

#424 Add support for --stream flag to 'onit get logs' command
  test/runner/cli.go
  test/runner/cluster.go
  test/runner/test.go
Labels: enhancement

#448 Store onit default cluster prior to cluster setup
  test/runner/cli.go
Labels: bug :beetle:

#449 Filter terminating namespaces from onit cluster list
  test/runner/controller.go
Labels: bug :beetle:

#451 Initialize config store when adding a device via northbound admin interface
  pkg/northbound/admin/admin_devices.go
Labels: bug :beetle:

#454 Adding a sleep in the subscribe test for consistency
  test/integration/subscribetest.go
Labels: bug :beetle:

#452 Provide progress report in console output when managing cluster resources with onit
  go.mod
  go.sum
  test/console/spinner.go
  test/console/status.go
  test/runner/atomix.go
  test/runner/cli.go
  test/runner/cluster.go
  test/runner/controller.go
  test/runner/onos-config.go
  test/runner/partitions.go
  test/runner/simulator.go
  test/runner/test.go
Labels: enhancement

#455 Ensure onit completion works in zsh and add completion for various arguments
  go.mod
  test/cli/cli.go
  test/cli/completion.go
  test/cli/config.go
  test/cmd/onit/main.go
  test/runner/cluster.go
  test/runner/config.go
Labels: enhancement
