Repository onosproject/onos-config, pull requests merged in 2019-07, with the labels that each got.

#466 Ignore plugin compile failures on certain OSes
  Makefile
Labels: bug :beetle:

#467 Ensure 'onit delete cluster' can delete multiple test clusters
  test/runner/atomix.go
  test/runner/cluster.go
  test/runner/controller.go
  test/runner/simulator.go
Labels: bug :beetle:

#468 Failing response checks after 50ms to avoid test hanging
  pkg/northbound/gnmi/subscribe_test.go
Labels: bug :beetle:

#469 Unset current cluster after delete
  test/cli/cli.go
Labels: bug :beetle:

#470 Default onos-config address in debug containers to local node
  build/onos-config-debug/Dockerfile
Labels: bug :beetle:

#471 Fixing inefficent assignemnt
  test/cli/cli.go
Labels: bug :beetle:

#475 Loading of ModelPlugins by default through Helm
  deployments/helm/onos-config/templates/deployment.yaml
  deployments/helm/onos-config/values.yaml
Labels: enhancement

#474 Load generated deviceStore.json even if empty
  deployments/helm/onos-config/templates/deployment.yaml
Labels: bug :beetle:

#436 Southbound error channel
  pkg/events/errorevent.go
  pkg/events/events.go
  pkg/manager/manager.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: enhancement, help wanted

#482 Added in strongly typed values for core
  pkg/store/change/typedvalue.go
  pkg/store/change/typedvalue_test.go
Labels: enhancement

#458 Adding spelling, cycles, assignment checks
  .travis.yml
  Makefile
  build/golang-build/Dockerfile
Labels: enhancement

#485 Typed values - added conversion functions
  pkg/store/change/typedvalue.go
  pkg/store/change/typedvalue_test.go
  pkg/utils/values/gnmiValueUtil.go
  pkg/utils/values/gnmiValueUtil_test.go
Labels: enhancement

#488 Changed TypedValue type to be an enumeration to be able to marshal it to JSON
  pkg/store/change/typedvalue.go
  pkg/store/change/typedvalue_test.go
  pkg/utils/values/gnmiValueUtil.go
Labels: enhancement

#489 Rollback method and usage
  pkg/manager/getconfig.go
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
  pkg/northbound/admin/admin.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/set.go
  pkg/store/stores.go
Labels: enhancement

#465 Stratum integration testing (#461)
  docs/testing.md
  test/cli/cli.go
  test/cli/completion.go
  test/runner/cluster.go
  test/runner/config.go
  test/runner/network.go
  test/runner/onos-config.go
  test/runner/simulator.go
  test/runner/test.go
Labels: enhancement

#494 Adding suites command and updating testing.md
  docs/testing.md
Labels: bug :beetle:, enhancement

#491 Changed core values to used strongly typed rather than string values
  cmd/profiling/profile-config.go
  configs/changeStore-sample.json
  configs/configStore-sample.json
  modelplugin/ModelGenerator.sh
  modelplugin/TestDevice-1.0.0/testdevice_1_0_0/generated.go
  modelplugin/yang/test1@2018-02-20.yang
  pkg/cli/command/devicetree.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
  pkg/manager/setconfig.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/gnmi/get.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/northbound/proto/diags.pb.go
  pkg/northbound/proto/diags.proto
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/change/change.go
  pkg/store/change/change_test.go
  pkg/store/change/changevalue.go
  pkg/store/change/configvalue.go
  pkg/store/change/typedvalue.go
  pkg/store/change/typedvalue_test.go
  pkg/store/store-api_test.go
  pkg/store/tree.go
  pkg/store/tree_test.go
  pkg/utils/values/gnmiChange.go
  pkg/utils/values/gnmiValueUtil.go
  pkg/utils/values/gnmiValueUtil_test.go
Labels: enhancement

#497 Re-adding subscribe test to intregration testing on travis
  test/integration/subscribetest.go
Labels: enhancement

#498 Rollback leaves the config there even if no changes are present
  pkg/store/stores.go
Labels: enhancement

#501 Change subscribe value and admin string formatting
  pkg/northbound/admin/admin.go
  test/integration/subscribetest.go
Labels: bug :beetle:

#500 Diags cmd - change - print the native types as string
  configs/changeStore-sample.json
  configs/configStore-sample.json
  docs/gnmi.md
  pkg/cli/command/changes.go
  pkg/cli/command/changes_test.go
  pkg/manager/setconfig.go
  pkg/northbound/diags/diags.go
  pkg/store/change/typedvalue.go
  pkg/store/change/typedvalue_test.go
Labels: enhancement

#503 Nil pointer fix and flag for model plugins
  docs/modelplugin.md
  docs/run.md
  pkg/northbound/gnmi/set.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: bug :beetle:

#502 Extraction of ModelPlugin YANG schema through admin gRPC
  docs/modelplugin.md
  modelplugin/Devicesim-1.0.0/modelmain.go
  modelplugin/ModelGenerator.sh
  modelplugin/TestDevice-1.0.0/modelmain.go
  modelplugin/TestDevice-2.0.0/modelmain.go
  modelplugin/TestDevice-2.0.0/testdevice_2_0_0/generated.go
  modelplugin/yang/test1@2019-06-10.yang
  pkg/cli/command/changes.go
  pkg/cli/command/models.go
  pkg/manager/modelregistry.go
  pkg/northbound/admin/admin.go
  pkg/northbound/proto/admin.pb.go
  pkg/northbound/proto/admin.proto
Labels: enhancement

#507 Bug fix on ExtractFullConfig - was changing values in change store
  pkg/manager/manager_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/gnmi/set_test.go
  pkg/store/change/change.go
  pkg/store/configuration.go
  pkg/store/store-api_test.go
Labels: bug :beetle:

#506 Rolling back also in case of fmt errors
  pkg/northbound/gnmi/set.go
Labels: bug :beetle:

#508 No Duplicate changes in device config
  pkg/manager/manager.go
  pkg/manager/rollbackconfig.go
  pkg/manager/setconfig.go
Labels: bug :beetle:

#509 Fixed hardcoding of devicetype in 'onos devices add ...'
  docs/cli.md
  pkg/northbound/admin/admin_devices.go
  pkg/northbound/admin/admin_test.go
  pkg/northbound/proto/admin.pb.go
  pkg/northbound/proto/admin.proto
  test/runner/onos-config.go
Labels: bug :beetle:

#514 Check for duplicate against just the last change ID. Fixes: #511
  pkg/manager/rollbackconfig.go
  pkg/northbound/gnmi/set.go
  pkg/store/configuration.go
Labels: bug :beetle:

#515 Test time-out increase. Fixes #512
  pkg/northbound/gnmi/subscribe_test.go
  test/integration/subscribetest.go
Labels: bug :beetle:

#516 Added checking of readonly types during Set
  docs/gnmi.md
  pkg/manager/manager.go
  pkg/manager/modelregistry.go
  pkg/manager/modelregistry_test.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/set.go
Labels: enhancement

#517 Removing comma before device type for onit to work
  test/runner/onos-config.go
Labels: bug :beetle:

#520 Addressing device tree bug Fixes #473 Fixes #519
  configs/deviceStore-sample.json
  docs/cli.md
  pkg/cli/command/changes.go
  pkg/cli/command/changes_test.go
  pkg/cli/command/devices.go
  pkg/cli/command/devicetree.go
  pkg/northbound/proto/admin.proto
  pkg/store/configuration.go
Labels: bug :beetle:

#521 Adding in gRPC-Web tool to proto Docker image
  build/protoc-go/Dockerfile
Labels: enhancement

#527 State and Operational paths from model
  pkg/manager/manager.go
  pkg/manager/modelregistry.go
  pkg/northbound/gnmi/set.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/utils/idUtils.go
Labels: enhancement

#484 Apply unconfined seccomp profile to debug containers run by onit
  test/runner/onos-config.go
Labels: bug :beetle:

#530 Added in certs for onos-config - moved tls.crt to client1.crt, reflecting it's subject
  deployments/helm/onos-config/files/certs/README.md
  deployments/helm/onos-config/files/certs/tls.crt
  deployments/helm/onos-config/files/certs/tls.key
  pkg/certs/default-certificates.go
  test/certs/client1.crt
  test/certs/client1.key
  test/certs/onf.cacrt
  test/certs/onos-config.crt
  test/certs/onos-config.key
  test/env/env.go
  test/runner/onos-config.go
Labels: bug :beetle:

#538 Extracting model registry as first entity object
  pkg/manager/manager.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
Labels: enhancement

#526 Query devices directly to make sure that changes were applied
  test/env/env.go
  test/integration/transactiontest.go
Labels: enhancement

#539 Optimized the calculation of ReadOnly paths from the model Plugins Fixes #525
  configs/changeStore-sample.json
  configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  docs/modelplugin.md
  modelplugin/Devicesim-1.0.0/devicesim-1.0.0.tree
  modelplugin/TestDevice-1.0.0/testdevice_1_0_0/generated.go
  modelplugin/TestDevice-2.0.0/testdevice_2_0_0/generated.go
  modelplugin/yang/openconfig-inet-types@2017-07-06.yang
  modelplugin/yang/test1@2018-02-20.yang
  modelplugin/yang/test1@2019-06-10.yang
  pkg/cli/command/models.go
  pkg/manager/manager.go
  pkg/manager/modelregistry.go
  pkg/manager/modelregistry_test.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/admin/admin.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/proto/admin.pb.go
  pkg/northbound/proto/admin.proto
Labels: enhancement

#540 Update codebase to model registry package
  cmd/onos-config/onos-config.go
  pkg/manager/manager.go
  pkg/manager/modelregistry.go
  pkg/manager/modelregistry_test.go
  pkg/manager/setconfig.go
  pkg/northbound/admin/admin.go
  pkg/northbound/gnmi/service.go
  pkg/northbound/gnmi/set.go
Labels: enhancement

#544 Added in ModelPlugins to the onit tool Fixes #537
  Makefile
  build/onos-config-debug/Dockerfile
  test/runner/onos-config.go
Labels: enhancement

#545 Config check before any set requests issued
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/set.go
Labels: bug :beetle:, enhancement

#546 Make debugging in onit easier
  build/onos-config-debug/Dockerfile
  docs/debugging.md
  docs/testing.md
Labels: WIP

#548 Adding type to R/O paths
  pkg/manager/manager.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/admin/admin.go
  pkg/northbound/gnmi/set.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/tree.go
Labels: enhancement

#550 Conversion of Json document in to native format - part 1 intermediate
  pkg/store/jsonToValues.go
  pkg/store/jsonToValues_test.go
  pkg/store/testdata/sample-tree.json
Labels: enhancement

#552 Added processing of JsonPaths buided by RO Paths - Part 2
  pkg/modelregistry/jsonvalues/convertJson_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig.json
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
Labels: enhancement

#562 Moved Devicesim yang files in to their own folder Fixes #561
  modelplugin/yang/Devicesim-1.0.0/ietf-inet-types@2013-07-15.yang
  modelplugin/yang/Devicesim-1.0.0/ietf-interfaces@2014-05-08.modified
  modelplugin/yang/Devicesim-1.0.0/ietf-yang-types@2013-07-15.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-aaa-radius@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-aaa-tacacs@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-aaa-types@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-aaa@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-extensions@2017-04-11.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-inet-types@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-interfaces@2017-07-14.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-openflow-types@2017-06-01.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-openflow@2017-06-01.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-platform-types@2016-12-22.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-platform@2016-12-22.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-procmon@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-system-logging@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-system-terminal@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-system@2017-07-06.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-types@2017-08-16.yang
  modelplugin/yang/Devicesim-1.0.0/openconfig-yang-types@2017-07-30.yang
Labels: enhancement

#564 Exposing json method and providing default case for number conversion
  pkg/modelregistry/jsonvalues/convertJson_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
Labels: bug :beetle:, enhancement

#565 Adding an extra test to jsonvalues
  pkg/store/jsonToValues_test.go
  pkg/store/testdata/sample-tree-from-devicesim.json
Labels: enhancement

#567 Adding model plugin for Stratum
  Makefile
  modelplugin/Stratum-1.0.0/modelmain.go
  modelplugin/Stratum-1.0.0/stratum_1_0_0/generated.go
  modelplugin/yang/Stratum-1.0.0/iana-if-type@2017-01-19.yang
  modelplugin/yang/Stratum-1.0.0/ietf-inet-types@2013-07-15.yang
  modelplugin/yang/Stratum-1.0.0/ietf-interfaces@2014-05-08-modified.yang
  modelplugin/yang/Stratum-1.0.0/ietf-yang-types@2013-07-15.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-aaa-radius@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-aaa-tacacs@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-aaa-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-aaa@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-alarm-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-alarms@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-extensions@2018-10-17.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-interfaces@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-platform-chassis@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-platform-linecard@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-platform-node@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-platform-port@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-platform@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules-qos@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-hercules@2018-06-01.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-if-aggregate@2019-04-16.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-if-ethernet@2019-04-16.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-if-ip@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-if-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-inet-types@2019-04-25.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-interfaces@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-lacp@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-messages@2018-08-13.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-packet-match-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-packet-match@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-platform-linecard@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-platform-port@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-platform-transceiver@2018-11-25.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-platform-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-platform@2019-04-16.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-procmon@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-qos-elements@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-qos-interfaces@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-qos-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-qos@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-system-logging@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-system-management@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-system-terminal@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-system2019-01-29.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-transport-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-types@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-vlan-types@2019-01-31.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-vlan@2018-11-21.yang
  modelplugin/yang/Stratum-1.0.0/openconfig-yang-types@2018-11-21.yang
Labels: enhancement

#568 Fix bug in readonly paths when multiple subpaths
  modelplugin/yang/test1@2019-06-10.yang
  pkg/modelregistry/jsonvalues/convertJson_test.go
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistryTestDevice1_test.go
  pkg/modelregistry/modelregistryTestDevice2_test.go
  pkg/modelregistry/modelregistry_test.go
Labels: bug :beetle:

#549 Integration test for model checking
  test/integration/gnmiutils.go
  test/integration/modelstest.go
  test/integration/protoutils.go
  test/integration/singlepathtest.go
  test/integration/subscribetest.go
  test/integration/transactiontest.go
Labels: enhancement

#574 Remove namespaces
  configs/changeStore-sample.json
  configs/configStore-sample.json
  deployments/helm/device-simulator/files/configs/ofsw_config.json
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  docs/cli.md
  docs/gnmi.md
  docs/gnmi_extensions.md
  docs/modelplugin.md
  docs/run.md
  pkg/manager/manager_test.go
  pkg/modelregistry/jsonvalues/convertJson_test.go
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig.json
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistryTestDevice1_test.go
  pkg/modelregistry/modelregistryTestDevice2_test.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/diags/diags_test.go
  pkg/northbound/gnmi/get_test.go
  pkg/northbound/gnmi/set_test.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/store/change/change_test.go
  pkg/store/jsonToValues_test.go
  pkg/store/store-api_test.go
  pkg/store/testdata/sample-tree-from-devicesim.json
  pkg/store/testdata/sample-tree.json
  pkg/store/tree_test.go
  test/configs/device/default.json
  test/integration/modelstest.go
  test/integration/singlepathtest.go
  test/integration/subscribetest.go
  test/integration/transactiontest.go
Labels: enhancement

#551 Add a debugging example using Golang IDE
  docs/debugging.md
  docs/images/goland_debug_connect.gif
  docs/images/goland_debug_set_breakpoints.gif
  docs/images/goland_debug_set_tracepoints.gif
  docs/images/goland_ide_remote_debug.gif
  docs/images/goland_log_and_evaluate.gif
Labels: enhancement

#576 Added in wildcard matching on Get and Subscribe on Northbound
  configs/changeStore-sample.json
  configs/configStore-sample.json
  pkg/manager/getconfig.go
  pkg/manager/manager_test.go
  pkg/northbound/gnmi/subscribe.go
  pkg/northbound/gnmi/subscribe_test.go
  pkg/utils/wildcards.go
  pkg/utils/wildcards_test.go
Labels: enhancement

#577 Fixed error in config and added doc for wildcard
  configs/changeStore-sample.json
  configs/configStore-sample.json
  deployments/helm/onos-config/files/configs/changeStore-sample.json
  deployments/helm/onos-config/files/configs/configStore-sample.json
  docs/gnmi.md
Labels: bug :beetle:

#578 Add onos-topo deployment to onit
  docs/testing.md
  test/cli/cli.go
  test/runner/cluster.go
  test/runner/common.go
  test/runner/config.go
  test/runner/onos-config.go
  test/runner/onos-topo.go
Labels: WIP, do not merge :warning:, enhancement

#585 Correct converJsonValues to handle same index twice
  pkg/modelregistry/jsonvalues/convertJson_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig2.json
Labels: bug :beetle:

#569 Read only state NB get
  docs/gnmi.md
  pkg/events/events.go
  pkg/manager/getstate.go
  pkg/manager/manager.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/modelregistry/modelregistry.go
  pkg/northbound/gnmi/get.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: enhancement

#590 Created TypedValueMap type Fixes #588
  pkg/manager/getstate.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/rollbackconfig.go
  pkg/manager/setconfig.go
  pkg/northbound/gnmi/set.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/store/change/typedvalue.go
Labels: enhancement

#589 State path Integration test
  test/integration/singlestatetest.go
Labels: enhancement

#592 Wildcard Integration Test
  build/onos-it/Dockerfile
  test/integration/_resources/address.json
  test/integration/_resources/addressState.json
  test/integration/_resources/allState.json
  test/integration/_resources/allStateAndConfig.json
  test/integration/gnmiutils.go
  test/integration/wildcardtest.go
Labels: enhancement
