Repository onosproject/onos-config, pull requests merged in 2020-09, with the labels that each got.

#1194 Update libraries to fix startup bugs
  go.mod
  go.sum
  pkg/store/change/device/store.go
  pkg/store/change/network/store.go
  pkg/store/leadership/store.go
  pkg/store/mastership/store.go
  pkg/store/snapshot/device/store.go
  pkg/store/snapshot/network/store.go
Labels: bug :beetle:

#1199 JSON handling: new method DecomposeJSONWithPaths for decomposing in to Path Values Fixes #1197
  pkg/modelregistry/jsonvalues/convertJsonRo_test.go
  pkg/modelregistry/jsonvalues/convertJsonRw_test.go
  pkg/modelregistry/jsonvalues/convertJsonTd2Rw_test.go
  pkg/modelregistry/jsonvalues/convertJsonTdRo_test.go
  pkg/modelregistry/jsonvalues/convertjson.go
  pkg/modelregistry/jsonvalues/jsonToValues.go
  pkg/modelregistry/jsonvalues/jsonToValues_test.go
  pkg/modelregistry/jsonvalues/testdata/sample-device1.json
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig-configuration.json
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig-double-index.json
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig2.json
  pkg/modelregistry/jsonvalues/testdata/sample-tree-double-key.json
  pkg/modelregistry/jsonvalues/testdata/sample-tree-from-devicesim.json
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistryDeviceSim1_test.go
  pkg/modelregistry/modelregistryTestDevice2_test.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/gnmi/set.go
  pkg/southbound/synchronizer/synchronizer.go
  pkg/southbound/synchronizer/synchronizer_test.go
  pkg/store/jsonToValues.go
  pkg/store/jsonToValues_test.go
  pkg/store/testdata/sample-tree.json
Labels: bug :beetle:

#1200 JSON Handling: decode LeafLists given in JSON values
  pkg/modelregistry/jsonvalues/convertJsonDs1_test.go
  pkg/modelregistry/jsonvalues/convertJsonRw_test.go
  pkg/modelregistry/jsonvalues/convertJsonTd2Rw_test.go
  pkg/modelregistry/jsonvalues/convertJsonTd2_test.go
  pkg/modelregistry/jsonvalues/convertJsonTdRo_test.go
  pkg/modelregistry/jsonvalues/jsonToValues.go
  pkg/modelregistry/jsonvalues/jsonToValues_test.go
  pkg/modelregistry/jsonvalues/testdata/sample-device1.json
  pkg/modelregistry/jsonvalues/testdata/sample-testdevice2-config.json
  pkg/modelregistry/jsonvalues/testdata/sample-testdevice2-opstate.json
Labels: bug :beetle:

#1203 NBI Set: take in to account path when handling JSON payloads
  .golangci.yml
  cmd/onos-config/onos-config.go
  onos-config.yaml
  pkg/manager/manager.go
  pkg/manager/manager_deep_test.go
  pkg/manager/manager_test.go
  pkg/modelregistry/jsonvalues/convertJsonDs1_test.go
  pkg/modelregistry/jsonvalues/convertJsonTd2_test.go
  pkg/modelregistry/jsonvalues/jsonToValues.go
  pkg/modelregistry/jsonvalues/jsonToValues_test.go
  pkg/modelregistry/jsonvalues/testdata/sample-tree-double-key.json
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistryDeviceSim1_test.go
  pkg/modelregistry/modelregistryTestDevice1_test.go
  pkg/modelregistry/modelregistryTestDevice2_test.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/admin/admin_test.go
  pkg/northbound/diags/diags_new_test.go
  pkg/northbound/gnmi/gnmi_test.go
  pkg/northbound/gnmi/set.go
  pkg/southbound/synchronizer/synchronizer.go
Labels: bug :beetle:

#1204 Integration test: gnmi suite. Fix treepath tests
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
Labels: bug :beetle:

#1207 Add multiple back to back set integration test
  go.mod
  go.sum
  test/gnmi/multiplesettest.go
Labels: enhancement

#1189 Employ mastership info for session management
  go.mod
  pkg/manager/devicehandler.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/southbound/synchronizer/device_update.go
  pkg/southbound/synchronizer/device_update_test.go
  pkg/southbound/synchronizer/factory.go
  pkg/southbound/synchronizer/session.go
  pkg/southbound/synchronizer/session_manager.go
  pkg/southbound/synchronizer/session_manager_test.go
  pkg/store/device/store.go
  pkg/test/mocks/device_service_client_mock.go
  test/gnmi/suite.go
Labels: enhancement

#1205 Modelregistry: fix bug in ExtractPaths
  pkg/modelregistry/jsonvalues/convertJsonTd2_test.go
  pkg/modelregistry/jsonvalues/jsonToValues.go
  pkg/modelregistry/jsonvalues/jsonToValues_test.go
  pkg/modelregistry/jsonvalues/testdata/sample-testdevice2-opstate.json
  pkg/modelregistry/modelregistry.go
  pkg/modelregistry/modelregistry_test.go
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
Labels: bug :beetle:

#1208 JSON gNMI Set: Fixed bug in DecomposeJSONWithPaths
  pkg/modelregistry/jsonvalues/convertJsonDs1_test.go
  pkg/modelregistry/jsonvalues/jsonToValues.go
  pkg/modelregistry/jsonvalues/jsonToValues_test.go
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig-configuration.json
  pkg/modelregistry/jsonvalues/testdata/sample-openconfig-double-index.json
  pkg/modelregistry/jsonvalues/testdata/sample-testdevice2-opstate.json
  pkg/modelregistry/jsonvalues/testdata/sample-tree-double-key.json
  pkg/northbound/gnmi/set.go
  pkg/northbound/gnmi/set_test.go
Labels: bug :beetle:

#1209 Add an HA test for session failover
  cmd/onos-config-tests/main.go
  pkg/southbound/synchronizer/device_update.go
  pkg/southbound/synchronizer/session.go
  test/ha/session_failover.go
  test/ha/suite.go
  test/utils/ha/utils.go
Labels: Testing

#1212 Remove initial set in synchronizer
  pkg/southbound/synchronizer/synchronizer.go
Labels: bug :beetle:, enhancement

#1219 Use backoff library function to retry in controllers
  go.mod
  pkg/controller/controller.go
  test/utils/gnmi/utils.go
Labels: enhancement
