Repository onosproject/onos-config, pull requests merged in 2020-02, with the labels that each got.

#1071 Test subscribe to an opstate cache path
  test/gnmi/subscribestatediagstest.go
  test/gnmi/subscribestategnmitest.go
  test/gnmi/subscribetest.go
  test/gnmi/subscribetestutils.go
Labels: Testing

#1074 Add the YGOT "generator" tool in to the toolset
  build/golang-build/Dockerfile
Labels: enhancement

#1076 Removed golang-build - has been moved to "../build-tools"
  build/golang-build/Dockerfile
  build/golang-build/README.md
  build/golang-build/dep-linux-amd64.sha256
Labels: enhancement

#955 Refactor reconciler API to allow controllers to requeue arbitrary changes
  pkg/controller/change/device/computedelta_test.go
  pkg/controller/change/device/controller.go
  pkg/controller/change/device/controller_test.go
  pkg/controller/change/network/controller.go
  pkg/controller/change/network/controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_mock_test.go
  pkg/controller/controller_test.go
  pkg/controller/snapshot/device/controller.go
  pkg/controller/snapshot/device/controller_test.go
  pkg/controller/snapshot/network/controller.go
  pkg/controller/snapshot/network/controller_test.go
Labels: do not merge :warning:

#1085 Moved the Docker file for the proto-go image in to build-tools
  build/protoc-go/Dockerfile
  build/protoc-go/README.md
Labels: enhancement
