Repository onosproject/onos-config, pull requests merged in 2020-01, with the labels that each got.

#1003 Update onos-config docs to use new onos-config commands
  docs/gnmi.md
  docs/run.md
Labels: documentation

#1005 Remove watch stream when closed to ensure watches are reopened on device connect
  pkg/controller/change/network/watcher.go
Labels: bug :beetle:

#1004 Test create remove device
  test/gnmi/createremovedevicetest.go
  test/utils/utils.go
Labels: Testing, enhancement

#1017 Re-queue NetworkChanges when device not found in device service
  pkg/controller/change/network/controller.go
  pkg/controller/controller.go
Labels: bug :beetle:

#1010 Make subsribe test utility functions more generic
  test/gnmi/subscribetest.go
Labels: Testing, enhancement

#1026 Added error handling to the GetSnapshot RPC on the Admin NBI Fixes #864
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin_test.go
  test/gnmi/snapshot.go
Labels: bug :beetle:

#1029 Added a test for CompactChanges and retrieve snapshot
  test/gnmi/compactChanges.go
  test/gnmi/createremovedevicetest.go
  test/gnmi/offlinedevicetest.go
  test/gnmi/offlineintopotest.go
  test/gnmi/oneliveonedeadtest.go
  test/gnmi/snapshot.go
  test/gnmi/transactiontest.go
  test/utils/utils.go
Labels: enhancement

#1032 Made snapshots CLI command consistent with other commands
  api/admin/admin.pb.go
  api/admin/admin.proto
  docs/api/admin.md
  pkg/cli/compactchanges.go
  pkg/cli/crud.go
  pkg/cli/mockclients_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/cli/snapshot.go
  pkg/northbound/admin/admin.go
  pkg/northbound/admin/admin_test.go
  pkg/store/snapshot/device/store.go
  pkg/test/mocks/store/device_snapshot_store_mock.go
  test/gnmi/compactChanges.go
  test/gnmi/snapshot.go
Labels: enhancement

#1033 Removing obsolete integration test gnmi/TestSnapshotErrors
  test/gnmi/snapshot.go
Labels: bug :beetle:

#1040 Updating gNMI docs with `type: STATE` and other corrections
  docs/gnmi.md
Labels: documentation

#1039 Fixes so can run the model code-generation on macOS
  modelplugin/ModelGenerator.sh
  modelplugin/yang/Devicesim-1.0.0/ietf-interfaces@2014-05-08.modified.yang
Labels: bug :beetle:

#1034 Changed List Response type in to an enum, for use in NBI, like topo
  api/diags/diags.pb.go
  api/diags/diags.proto
  docs/api/diags.md
  pkg/manager/manager_test.go
  pkg/northbound/diags/diags.go
  pkg/northbound/diags/diags_new_test.go
  pkg/test/mocks/store/map_backed_network_changes_store_mock.go
Labels: enhancement

#1047 Track change/rollback indexes in device state machine
  pkg/store/change/device/state/store.go
Labels: bug :beetle:

#1050 Ensure device state is correctly computed for rollbacks in device state store
  pkg/store/change/device/state/store.go
Labels: bug :beetle:

#1066 Fixed problems with watching OpState Fixes #1063
  pkg/dispatcher/dispatcher.go
  pkg/manager/manager.go
Labels: bug :beetle:

#1065 Upgraded to new version and package names of Atomix
  go.mod
  go.sum
  pkg/store/change/device/store.go
  pkg/store/change/network/store.go
  pkg/store/device/store.go
  pkg/store/leadership/store.go
  pkg/store/mastership/election.go
  pkg/store/mastership/store.go
  pkg/store/snapshot/device/store.go
  pkg/store/snapshot/network/store.go
  pkg/store/utils/atomix.go
  pkg/test/mocks/store/device_changes_store_mock.go
  pkg/test/mocks/store/network_changes_store_mock.go
Labels: enhancement

#1067 Improved handling of OpState stream close
  pkg/northbound/diags/diags.go
Labels: bug :beetle:
